# Site settings
title: Rebelliously refusing to make a clever blog title
email: logustus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts of a software engineer, miniature painter, sword sparer(?), father, and other labels I forgot about. This blog is brought to you by the byproducts of a dead star.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://blog.logustus.com" # the base hostname & protocol for your site
twitter_username: logan_barnett
github_username:  LoganBarnett

# Build settings
markdown: kramdown

