# Site settings
title: Logan Barnett's blog
email: logustus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts of a software engineer, miniature painter, sword sparer(?), father, and other labels I forgot about. This blog is brought to you by the byproducts of a dead star.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://blog.logustus.com" # the base hostname & protocol for your site
twitter_username: logan_barnett
github_username:  LoganBarnett

exclude: [
  "_posts/*.org",
  "*.org",
  "vendor"
  ]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  coderay_line_numbers: inline

# static assets
static_files: /assets

# github-pages doesn't respect this, so it doesn't matter what we set it to.
# This means we can't use _plugins/foo.rb styled plugins.  See
# http://jekyllrb.com/docs/plugins/installation/ for citation.
# safe: false

# This disables the linking of blog posts to dates and categories, with titles
# being a sort of after-thought.  We just want the title and its extension.
# Even the "none" option in
# https://jekyllrb.com/docs/permalinks/#built-in-formats comes with "something"
# (categories).
permalink: ":title:output_ext"

#markdown: redcarpet
#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "no_intra_emphasis"]
