# Site settings
title: Logan Barnett's blog
email: logustus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts of a software engineer, miniature painter, sword sparer(?), father, and other labels I forgot about. This blog is brought to you by the byproducts of a dead star.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://blog.logustus.com" # the base hostname & protocol for your site
twitter_username: logan_barnett
github_username:  LoganBarnett

exclude: [
  "_posts/*.org",
  "vendor"
  ]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  coderay_line_numbers: inline

# static assets
static_files: /assets


#markdown: redcarpet
#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "no_intra_emphasis"]
