#+BEGIN_EXPORT html
---
layout: default
title: Software Engineering - Starter Web app
date: 2018-06-13
categories: software-engineering
---
#+END_EXPORT

#+title:    Software Engineering - Starter Web app
#+author:   Logan Barnett
#+email:    logustus@gmail.com
#+date:     <2018-06-13 Wed>
#+language: en
#+tags:     tutorials software web
#+auto_id: t

Hi there! I believe questions are wonderful opportunities to enhance
documentation. In this case I've put together a series of posts for putting
together your first web application using this buzzword list: HTML, CSS,
Node.js, Express.js, bash (or just a shell), yarn, git, Homebrew, and maybe some
other stuff I forgot to include.

+ [[./software-engineering-starter-web-01.org][part 1 - getting set up with your local environment, and a tiny server]]
+ [[./software-engineering-starter-web-02.org][part 2 - using curl, mime types, and fulfilling an automated test]]
+ [[./software-engineering-starter-web-03.org][part 3 - working with data]]
+ [[./software-engineering-starter-web-04.org][part 4 - backing it all up with git]]

While this isn't complete, I'll expand upon it anytime I get a chance to help
someone pick up the trade. Don't worry if it seems like a lot! Fairly consistent
exposure will keep you moving along the never-ending fractal that is learning
about software engineering.
